// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.9.178
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MadsKristensen.ToggleFeatures
{
    static class Vsix
    {
        public const string Id = "4ce74140-3f68-4438-92a4-a54afea98179";
        public const string Name = "Disable Solution Explorer's Dynamic Nodes";
        public const string Description = "A single-purpose extension that makes it easy to disable/enable Solution Explorer's dynamic nodes such inline Class View nodes from C# and VB files. ";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "Solution Explorer, enable, disable, IGraphProvider";
    }
}
